/* WARNING: This file will be overwritten by the plugin.
Do not edit this file directly! First copy this file and rename it if you want to edit things. */

:root {
}
/* @settings
name: Supercharged Links
id: supercharged-links
settings:
*/